name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Make repo pushable
      env:
        GITHUB_USER: ${{ secrets.BEPIN_BOT_USER }}
        GITHUB_PAT: ${{ secrets.BEPIN_BOT_PAT }}
      shell: bash
      run: git remote set-url --push origin https://$GITHUB_USER:$GITHUB_PAT@github.com/$GITHUB_REPOSITORY.git
      
    - name: Run build script
      run: ./build.ps1 --target=Build
      
    - name: Create a release tag
      if: github.ref == 'refs/heads/main'
      env:
        NUGET_KEY: ${{ secrets.BEPIN_DEV_NUGET_KEY }}
        NUGET_NAME: ${{ secrets.BEPIN_DEV_NUGET_SOURCE }}
      run: ./build.ps1 --target=Publish --nugetKey="${env:NUGET_KEY}" -nugetSource="${env:NUGET_NAME}"
      
    - name: Get target file
      id: getfilename
      shell: bash
      run: echo "::set-output name=file::$(ls ./BepInEx.Analyzers/BepInEx.Analyzers.Package/bin/Nuget/BepInEx.Analyzers*.nupkg)"
      
    - uses: actions/upload-artifact@v1
      with:
        path: ${{ steps.getfilename.outputs.file }}
        name: BepInEx.Analyzers
